baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kaitai.io" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown

plugins:
  - jekyll-redirect-from

exclude:
    - README.md
